'use strict';
// tasks.js — durable structured task storage (P0).
// Replaces fragile Markdown-derived task IDs with a SQLite-compatible JSON
// store keyed by stable UUID. Markdown is an export/sync view, not source of truth.
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const paths = require('./paths');

let _db = null;

function loadDb() {
  if (_db) return _db;
  const file = paths.tasksDbPath();
  fs.mkdirSync(path.dirname(file), { recursive: true });
  if (!fs.existsSync(file)) {
    _db = { version: 1, tasks: [], nextDisplay: 1 };
    saveDb();
    return _db;
  }
  try {
    _db = JSON.parse(fs.readFileSync(file, 'utf8'));
    if (!_db.version) _db.version = 1;
    if (!_db.nextDisplay) _db.nextDisplay = 1;
    return _db;
  } catch {
    // corrupt db — back it up, start fresh
    fs.writeFileSync(`${file}.corrupt-${Date.now()}`, fs.readFileSync(file));
    _db = { version: 1, tasks: [], nextDisplay: 1 };
    saveDb();
    return _db;
  }
}

function saveDb() {
  fs.mkdirSync(path.dirname(paths.tasksDbPath()), { recursive: true });
  fs.writeFileSync(paths.tasksDbPath(), JSON.stringify(_db, null, 2), { mode: 0o600 });
}

function newId() { return crypto.randomUUID(); }

// ---- CRUD -------------------------------------------------------------
function add({ title, description = '', status = 'open', project = null, assignedAgent = null, source = null, dependencies = [], tags = [], verification = {} }) {
  const db = loadDb();
  const now = new Date().toISOString();
  const task = {
    id: newId(),
    display: db.nextDisplay,
    title,
    description,
    status, // open | in_progress | completed | cancelled
    created_at: now,
    updated_at: now,
    completed_at: null,
    project,
    assigned_agent: assignedAgent,
    source,
    dependencies,
    tags,
    verification,
  };
  db.tasks.push(task);
  db.nextDisplay += 1;
  saveDb();
  return task;
}

function list(filter = {}) {
  const db = loadDb();
  let tasks = db.tasks.slice();
  if (filter.status) tasks = tasks.filter((t) => t.status === filter.status);
  if (filter.project) tasks = tasks.filter((t) => t.project === filter.project);
  return tasks;
}

function getById(id) {
  const db = loadDb();
  const byId = db.tasks.find((t) => t.id === id);
  if (byId) return byId;
  const byDisplay = db.tasks.find((t) => String(t.display) === String(id));
  return byDisplay || null;
}

function update(id, changes) {
  const db = loadDb();
  const t = getById(id);
  if (!t) return null;
  Object.assign(t, changes);
  t.updated_at = new Date().toISOString();
  if (t.status === 'completed' && !t.completed_at) t.completed_at = new Date().toISOString();
  saveDb();
  return t;
}

function complete(id) { return update(id, { status: 'completed' }); }
function reopen(id) { return update(id, { status: 'open', completed_at: null }); }
function remove(id) {
  const db = loadDb();
  const i = db.tasks.findIndex((t) => t.id === id || String(t.display) === String(id));
  if (i < 0) return false;
  db.tasks.splice(i, 1);
  saveDb();
  return true;
}

// ---- Markdown export (view, not source of truth) --------------------------
function markdownFile() {
  const ws = paths.defaultWorkspace();
  return path.join(ws, 'Agent Hub', 'Tasks.md');
}

function toMarkdown() {
  const db = loadDb();
  const lines = ['# Tasks', '', '<!-- Generated by AgentStack. Source of truth: data/agentstack.db -->', ''];
  for (const t of db.tasks) {
    const box = t.status === 'completed' ? '[x]' : '[ ]';
    lines.push(`- ${box} ${t.display}. ${t.title}${t.status === 'completed' ? ' (done)' : ''}`);
  }
  return lines.join('\n') + '\n';
}

function exportMarkdown(fileOverride) {
  const file = fileOverride || markdownFile();
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, toMarkdown());
  return file;
}

// ---- Migration: import from legacy Tasks.md (backup + preserve) ----------
function migrateFromLegacy(fileOverride) {
  const file = fileOverride || markdownFile();
  const db = loadDb();
  const report = { file, backedUp: false, imported: 0, skipped: 0, duplicates: 0 };
  if (!fs.existsSync(file)) return { ...report, reason: 'no legacy file' };
  // backup
  const backup = `${file}.bak-${Date.now()}`;
  fs.copyFileSync(file, backup);
  report.backedUp = backup;

  const content = fs.readFileSync(file, 'utf8');
  const seen = new Set(db.tasks.map((t) => t.title.toLowerCase()));
  for (const line of content.split('\n')) {
    const m = line.match(/^\s*-\s*\[(x| )\]\s*(?:(\d+)\.\s*)?(.+?)\s*$/i);
    if (!m) continue;
    const status = m[1].toLowerCase() === 'x' ? 'completed' : 'open';
    const title = m[3].trim();
    if (!title) continue;
    if (seen.has(title.toLowerCase())) { report.duplicates++; continue; }
    add({ title, status, source: 'legacy-migration' });
    seen.add(title.toLowerCase());
    report.imported++;
  }
  // write fresh markdown view (without legacy header junk)
  exportMarkdown(file);
  return report;
}

module.exports = {
  add, list, getById, update, complete, reopen, remove,
  exportMarkdown, toMarkdown, migrateFromLegacy, markdownFile, newId,
};
